stages:
  - build

build_et_push_dockerhub:
  stage: build
  tags:
    - windows
  script:
    - echo "Connexion a Docker Hub..."
    - docker login -u $env:DOCKER_USER -p $env:DOCKER_PASSWORD
    - echo "Construction de l'image..."
    - docker build -t makitetsuu/makidocker:latest .
    - echo "Envoi..."
    - docker push makitetsuu/makidocker:latest
  only:
    - main