stages:
  - build

build-site:
  stage: build
  tags:
    - windows
  script:
    - docker login -u gitlab-ci-token -p $env:CI_JOB_TOKEN $env:CI_REGISTRY
    - docker build -t "$env:CI_REGISTRY_IMAGE:$env:CI_COMMIT_REF_SLUG" .
    - docker push "$env:CI_REGISTRY_IMAGE:$env:CI_COMMIT_REF_SLUG"
  only:
    - main